### PR TITLE
Fix includedir

### PR DESCRIPTION
**Pull request by klemensn**
noson-app code uses `<noson/*.h>`, so building that against noson as system library will fail as `<noson/noson/*.h>` does not exist.

This is the case on OpenBSD where /usr/local/ is the default prefix. On Linux, the default is /usr/, i.e. the same as the default prefix.

My guess it's been working by accident so far.

### CODE REVIEW

**Comment by janbar** [comment]
Installed headers must be in a subfolder in the include dir i.e "noson", as headers could override others file of the system.
I guess the issue is not here, but in the other project noson-app. Also that is preferable to link noson-app statically with the this project because the  C++ ABI is not stable. That is the reason noson-app has a submodule that points to a particular commit and it is linked statically with it. 
I will check the issue trying to link dynamically...

**Comment by klemensn** [comment]
> Installed headers must be in a subfolder in the include dir i.e "noson", as headers could override others file of the system.
> I guess the issue is not here, but in the other project noson-app. Also that is preferable to link noson-app statically with this project because the  C++ ABI is not stable.

That's fine, splitting it out as its own lib remains preferred for me as package maintainer.

> That is the reason noson-app has a submodule that points to a particular commit and it is linked statically with it. 
> I will check the issue trying to link dynamically... 

The issue is not static vs. dynamic, but bundled vs. extern/system library.

Using libnoson.a won't change how noson-app looks for the header.

**Comment by janbar** [comment]
Sorry, I didn't see this commit fix pkg config and cmake config. So it is OK.

**Comment by janbar** [comment]
@klemensn , Thanks

**Pull request merged**
